services:
  postgres:
    image: postgres:18.0-alpine
    container_name: ciam-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ciam
    restart: no