// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AuthRequest is an object representing the database table.
type AuthRequest struct {
	ID                  string            `boil:"id" json:"id" toml:"id" yaml:"id"`
	ClientID            string            `boil:"client_id" json:"client_id" toml:"client_id" yaml:"client_id"`
	Subject             string            `boil:"subject" json:"subject" toml:"subject" yaml:"subject"`
	RedirectURI         string            `boil:"redirect_uri" json:"redirect_uri" toml:"redirect_uri" yaml:"redirect_uri"`
	Scopes              types.StringArray `boil:"scopes" json:"scopes" toml:"scopes" yaml:"scopes"`
	ResponseType        string            `boil:"response_type" json:"response_type" toml:"response_type" yaml:"response_type"`
	ResponseMode        string            `boil:"response_mode" json:"response_mode" toml:"response_mode" yaml:"response_mode"`
	State               string            `boil:"state" json:"state" toml:"state" yaml:"state"`
	Nonce               string            `boil:"nonce" json:"nonce" toml:"nonce" yaml:"nonce"`
	LoginHint           string            `boil:"login_hint" json:"login_hint" toml:"login_hint" yaml:"login_hint"`
	CodeChallenge       string            `boil:"code_challenge" json:"code_challenge" toml:"code_challenge" yaml:"code_challenge"`
	CodeChallengeMethod string            `boil:"code_challenge_method" json:"code_challenge_method" toml:"code_challenge_method" yaml:"code_challenge_method"`
	AuthTime            null.Time         `boil:"auth_time" json:"auth_time,omitempty" toml:"auth_time" yaml:"auth_time,omitempty"`
	CreatedAt           time.Time         `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ExpiresAt           time.Time         `boil:"expires_at" json:"expires_at" toml:"expires_at" yaml:"expires_at"`

	R *authRequestR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L authRequestL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AuthRequestColumns = struct {
	ID                  string
	ClientID            string
	Subject             string
	RedirectURI         string
	Scopes              string
	ResponseType        string
	ResponseMode        string
	State               string
	Nonce               string
	LoginHint           string
	CodeChallenge       string
	CodeChallengeMethod string
	AuthTime            string
	CreatedAt           string
	ExpiresAt           string
}{
	ID:                  "id",
	ClientID:            "client_id",
	Subject:             "subject",
	RedirectURI:         "redirect_uri",
	Scopes:              "scopes",
	ResponseType:        "response_type",
	ResponseMode:        "response_mode",
	State:               "state",
	Nonce:               "nonce",
	LoginHint:           "login_hint",
	CodeChallenge:       "code_challenge",
	CodeChallengeMethod: "code_challenge_method",
	AuthTime:            "auth_time",
	CreatedAt:           "created_at",
	ExpiresAt:           "expires_at",
}

var AuthRequestTableColumns = struct {
	ID                  string
	ClientID            string
	Subject             string
	RedirectURI         string
	Scopes              string
	ResponseType        string
	ResponseMode        string
	State               string
	Nonce               string
	LoginHint           string
	CodeChallenge       string
	CodeChallengeMethod string
	AuthTime            string
	CreatedAt           string
	ExpiresAt           string
}{
	ID:                  "auth_request.id",
	ClientID:            "auth_request.client_id",
	Subject:             "auth_request.subject",
	RedirectURI:         "auth_request.redirect_uri",
	Scopes:              "auth_request.scopes",
	ResponseType:        "auth_request.response_type",
	ResponseMode:        "auth_request.response_mode",
	State:               "auth_request.state",
	Nonce:               "auth_request.nonce",
	LoginHint:           "auth_request.login_hint",
	CodeChallenge:       "auth_request.code_challenge",
	CodeChallengeMethod: "auth_request.code_challenge_method",
	AuthTime:            "auth_request.auth_time",
	CreatedAt:           "auth_request.created_at",
	ExpiresAt:           "auth_request.expires_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_StringArray struct{ field string }

func (w whereHelpertypes_StringArray) EQ(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_StringArray) NEQ(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_StringArray) LT(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_StringArray) LTE(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_StringArray) GT(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_StringArray) GTE(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var AuthRequestWhere = struct {
	ID                  whereHelperstring
	ClientID            whereHelperstring
	Subject             whereHelperstring
	RedirectURI         whereHelperstring
	Scopes              whereHelpertypes_StringArray
	ResponseType        whereHelperstring
	ResponseMode        whereHelperstring
	State               whereHelperstring
	Nonce               whereHelperstring
	LoginHint           whereHelperstring
	CodeChallenge       whereHelperstring
	CodeChallengeMethod whereHelperstring
	AuthTime            whereHelpernull_Time
	CreatedAt           whereHelpertime_Time
	ExpiresAt           whereHelpertime_Time
}{
	ID:                  whereHelperstring{field: "\"auth_request\".\"id\""},
	ClientID:            whereHelperstring{field: "\"auth_request\".\"client_id\""},
	Subject:             whereHelperstring{field: "\"auth_request\".\"subject\""},
	RedirectURI:         whereHelperstring{field: "\"auth_request\".\"redirect_uri\""},
	Scopes:              whereHelpertypes_StringArray{field: "\"auth_request\".\"scopes\""},
	ResponseType:        whereHelperstring{field: "\"auth_request\".\"response_type\""},
	ResponseMode:        whereHelperstring{field: "\"auth_request\".\"response_mode\""},
	State:               whereHelperstring{field: "\"auth_request\".\"state\""},
	Nonce:               whereHelperstring{field: "\"auth_request\".\"nonce\""},
	LoginHint:           whereHelperstring{field: "\"auth_request\".\"login_hint\""},
	CodeChallenge:       whereHelperstring{field: "\"auth_request\".\"code_challenge\""},
	CodeChallengeMethod: whereHelperstring{field: "\"auth_request\".\"code_challenge_method\""},
	AuthTime:            whereHelpernull_Time{field: "\"auth_request\".\"auth_time\""},
	CreatedAt:           whereHelpertime_Time{field: "\"auth_request\".\"created_at\""},
	ExpiresAt:           whereHelpertime_Time{field: "\"auth_request\".\"expires_at\""},
}

// AuthRequestRels is where relationship names are stored.
var AuthRequestRels = struct {
	Client string
}{
	Client: "Client",
}

// authRequestR is where relationships are stored.
type authRequestR struct {
	Client *Client `boil:"Client" json:"Client" toml:"Client" yaml:"Client"`
}

// NewStruct creates a new relationship struct
func (*authRequestR) NewStruct() *authRequestR {
	return &authRequestR{}
}

func (o *AuthRequest) GetClient() *Client {
	if o == nil {
		return nil
	}

	return o.R.GetClient()
}

func (r *authRequestR) GetClient() *Client {
	if r == nil {
		return nil
	}

	return r.Client
}

// authRequestL is where Load methods for each relationship are stored.
type authRequestL struct{}

var (
	authRequestAllColumns            = []string{"id", "client_id", "subject", "redirect_uri", "scopes", "response_type", "response_mode", "state", "nonce", "login_hint", "code_challenge", "code_challenge_method", "auth_time", "created_at", "expires_at"}
	authRequestColumnsWithoutDefault = []string{"id", "client_id", "expires_at"}
	authRequestColumnsWithDefault    = []string{"subject", "redirect_uri", "scopes", "response_type", "response_mode", "state", "nonce", "login_hint", "code_challenge", "code_challenge_method", "auth_time", "created_at"}
	authRequestPrimaryKeyColumns     = []string{"id"}
	authRequestGeneratedColumns      = []string{}
)

type (
	// AuthRequestSlice is an alias for a slice of pointers to AuthRequest.
	// This should almost always be used instead of []AuthRequest.
	AuthRequestSlice []*AuthRequest
	// AuthRequestHook is the signature for custom AuthRequest hook methods
	AuthRequestHook func(context.Context, boil.ContextExecutor, *AuthRequest) error

	authRequestQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	authRequestType                 = reflect.TypeOf(&AuthRequest{})
	authRequestMapping              = queries.MakeStructMapping(authRequestType)
	authRequestPrimaryKeyMapping, _ = queries.BindMapping(authRequestType, authRequestMapping, authRequestPrimaryKeyColumns)
	authRequestInsertCacheMut       sync.RWMutex
	authRequestInsertCache          = make(map[string]insertCache)
	authRequestUpdateCacheMut       sync.RWMutex
	authRequestUpdateCache          = make(map[string]updateCache)
	authRequestUpsertCacheMut       sync.RWMutex
	authRequestUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var authRequestAfterSelectMu sync.Mutex
var authRequestAfterSelectHooks []AuthRequestHook

var authRequestBeforeInsertMu sync.Mutex
var authRequestBeforeInsertHooks []AuthRequestHook
var authRequestAfterInsertMu sync.Mutex
var authRequestAfterInsertHooks []AuthRequestHook

var authRequestBeforeUpdateMu sync.Mutex
var authRequestBeforeUpdateHooks []AuthRequestHook
var authRequestAfterUpdateMu sync.Mutex
var authRequestAfterUpdateHooks []AuthRequestHook

var authRequestBeforeDeleteMu sync.Mutex
var authRequestBeforeDeleteHooks []AuthRequestHook
var authRequestAfterDeleteMu sync.Mutex
var authRequestAfterDeleteHooks []AuthRequestHook

var authRequestBeforeUpsertMu sync.Mutex
var authRequestBeforeUpsertHooks []AuthRequestHook
var authRequestAfterUpsertMu sync.Mutex
var authRequestAfterUpsertHooks []AuthRequestHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AuthRequest) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range authRequestAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AuthRequest) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range authRequestBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AuthRequest) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range authRequestAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AuthRequest) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range authRequestBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AuthRequest) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range authRequestAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AuthRequest) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range authRequestBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AuthRequest) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range authRequestAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AuthRequest) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range authRequestBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AuthRequest) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range authRequestAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAuthRequestHook registers your hook function for all future operations.
func AddAuthRequestHook(hookPoint boil.HookPoint, authRequestHook AuthRequestHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		authRequestAfterSelectMu.Lock()
		authRequestAfterSelectHooks = append(authRequestAfterSelectHooks, authRequestHook)
		authRequestAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		authRequestBeforeInsertMu.Lock()
		authRequestBeforeInsertHooks = append(authRequestBeforeInsertHooks, authRequestHook)
		authRequestBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		authRequestAfterInsertMu.Lock()
		authRequestAfterInsertHooks = append(authRequestAfterInsertHooks, authRequestHook)
		authRequestAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		authRequestBeforeUpdateMu.Lock()
		authRequestBeforeUpdateHooks = append(authRequestBeforeUpdateHooks, authRequestHook)
		authRequestBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		authRequestAfterUpdateMu.Lock()
		authRequestAfterUpdateHooks = append(authRequestAfterUpdateHooks, authRequestHook)
		authRequestAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		authRequestBeforeDeleteMu.Lock()
		authRequestBeforeDeleteHooks = append(authRequestBeforeDeleteHooks, authRequestHook)
		authRequestBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		authRequestAfterDeleteMu.Lock()
		authRequestAfterDeleteHooks = append(authRequestAfterDeleteHooks, authRequestHook)
		authRequestAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		authRequestBeforeUpsertMu.Lock()
		authRequestBeforeUpsertHooks = append(authRequestBeforeUpsertHooks, authRequestHook)
		authRequestBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		authRequestAfterUpsertMu.Lock()
		authRequestAfterUpsertHooks = append(authRequestAfterUpsertHooks, authRequestHook)
		authRequestAfterUpsertMu.Unlock()
	}
}

// One returns a single authRequest record from the query.
func (q authRequestQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AuthRequest, error) {
	o := &AuthRequest{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: failed to execute a one query for auth_request")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AuthRequest records from the query.
func (q authRequestQuery) All(ctx context.Context, exec boil.ContextExecutor) (AuthRequestSlice, error) {
	var o []*AuthRequest

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "orm: failed to assign all query results to AuthRequest slice")
	}

	if len(authRequestAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AuthRequest records in the query.
func (q authRequestQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to count auth_request rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q authRequestQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "orm: failed to check if auth_request exists")
	}

	return count > 0, nil
}

// Client pointed to by the foreign key.
func (o *AuthRequest) Client(mods ...qm.QueryMod) clientQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ClientID),
	}

	queryMods = append(queryMods, mods...)

	return Clients(queryMods...)
}

// LoadClient allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (authRequestL) LoadClient(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAuthRequest any, mods queries.Applicator) error {
	var slice []*AuthRequest
	var object *AuthRequest

	if singular {
		var ok bool
		object, ok = maybeAuthRequest.(*AuthRequest)
		if !ok {
			object = new(AuthRequest)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAuthRequest)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAuthRequest))
			}
		}
	} else {
		s, ok := maybeAuthRequest.(*[]*AuthRequest)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAuthRequest)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAuthRequest))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &authRequestR{}
		}
		args[object.ClientID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &authRequestR{}
			}

			args[obj.ClientID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`client`),
		qm.WhereIn(`client.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Client")
	}

	var resultSlice []*Client
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Client")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for client")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for client")
	}

	if len(clientAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Client = foreign
		if foreign.R == nil {
			foreign.R = &clientR{}
		}
		foreign.R.AuthRequests = append(foreign.R.AuthRequests, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ClientID == foreign.ID {
				local.R.Client = foreign
				if foreign.R == nil {
					foreign.R = &clientR{}
				}
				foreign.R.AuthRequests = append(foreign.R.AuthRequests, local)
				break
			}
		}
	}

	return nil
}

// SetClient of the authRequest to the related item.
// Sets o.R.Client to related.
// Adds o to related.R.AuthRequests.
func (o *AuthRequest) SetClient(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Client) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"auth_request\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"client_id"}),
		strmangle.WhereClause("\"", "\"", 2, authRequestPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ClientID = related.ID
	if o.R == nil {
		o.R = &authRequestR{
			Client: related,
		}
	} else {
		o.R.Client = related
	}

	if related.R == nil {
		related.R = &clientR{
			AuthRequests: AuthRequestSlice{o},
		}
	} else {
		related.R.AuthRequests = append(related.R.AuthRequests, o)
	}

	return nil
}

// AuthRequests retrieves all the records using an executor.
func AuthRequests(mods ...qm.QueryMod) authRequestQuery {
	mods = append(mods, qm.From("\"auth_request\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"auth_request\".*"})
	}

	return authRequestQuery{q}
}

// FindAuthRequest retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAuthRequest(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*AuthRequest, error) {
	authRequestObj := &AuthRequest{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"auth_request\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, authRequestObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: unable to select from auth_request")
	}

	if err = authRequestObj.doAfterSelectHooks(ctx, exec); err != nil {
		return authRequestObj, err
	}

	return authRequestObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AuthRequest) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("orm: no auth_request provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(authRequestColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	authRequestInsertCacheMut.RLock()
	cache, cached := authRequestInsertCache[key]
	authRequestInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			authRequestAllColumns,
			authRequestColumnsWithDefault,
			authRequestColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(authRequestType, authRequestMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(authRequestType, authRequestMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"auth_request\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"auth_request\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "orm: unable to insert into auth_request")
	}

	if !cached {
		authRequestInsertCacheMut.Lock()
		authRequestInsertCache[key] = cache
		authRequestInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AuthRequest.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AuthRequest) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	authRequestUpdateCacheMut.RLock()
	cache, cached := authRequestUpdateCache[key]
	authRequestUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			authRequestAllColumns,
			authRequestPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("orm: unable to update auth_request, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"auth_request\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, authRequestPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(authRequestType, authRequestMapping, append(wl, authRequestPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update auth_request row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by update for auth_request")
	}

	if !cached {
		authRequestUpdateCacheMut.Lock()
		authRequestUpdateCache[key] = cache
		authRequestUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q authRequestQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all for auth_request")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected for auth_request")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AuthRequestSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("orm: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), authRequestPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"auth_request\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, authRequestPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all in authRequest slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected all in update all authRequest")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AuthRequest) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("orm: no auth_request provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(authRequestColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	authRequestUpsertCacheMut.RLock()
	cache, cached := authRequestUpsertCache[key]
	authRequestUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			authRequestAllColumns,
			authRequestColumnsWithDefault,
			authRequestColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			authRequestAllColumns,
			authRequestPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("orm: unable to upsert auth_request, could not build update column list")
		}

		ret := strmangle.SetComplement(authRequestAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(authRequestPrimaryKeyColumns) == 0 {
				return errors.New("orm: unable to upsert auth_request, could not build conflict column list")
			}

			conflict = make([]string, len(authRequestPrimaryKeyColumns))
			copy(conflict, authRequestPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"auth_request\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(authRequestType, authRequestMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(authRequestType, authRequestMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "orm: unable to upsert auth_request")
	}

	if !cached {
		authRequestUpsertCacheMut.Lock()
		authRequestUpsertCache[key] = cache
		authRequestUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AuthRequest record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AuthRequest) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("orm: no AuthRequest provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), authRequestPrimaryKeyMapping)
	sql := "DELETE FROM \"auth_request\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete from auth_request")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by delete for auth_request")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q authRequestQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("orm: no authRequestQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from auth_request")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for auth_request")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AuthRequestSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(authRequestBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), authRequestPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"auth_request\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, authRequestPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from authRequest slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for auth_request")
	}

	if len(authRequestAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AuthRequest) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAuthRequest(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AuthRequestSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AuthRequestSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), authRequestPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"auth_request\".* FROM \"auth_request\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, authRequestPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "orm: unable to reload all in AuthRequestSlice")
	}

	*o = slice

	return nil
}

// AuthRequestExists checks if the AuthRequest row exists.
func AuthRequestExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"auth_request\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "orm: unable to check if auth_request exists")
	}

	return exists, nil
}

// Exists checks if the AuthRequest row exists.
func (o *AuthRequest) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AuthRequestExists(ctx, exec, o.ID)
}
