// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	AuthRequest string
	Client      string
	Migrations  string
}{
	AuthRequest: "auth_request",
	Client:      "client",
	Migrations:  "migrations",
}
