// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockclient

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuanta7/ciam/internal/repository/store"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateClient provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateClient(ctx context.Context, arg store.CreateClientParams) (store.Client, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateClient")
	}

	var r0 store.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateClientParams) (store.Client, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreateClientParams) store.Client); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(store.Client)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.CreateClientParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClient'
type MockRepository_CreateClient_Call struct {
	*mock.Call
}

// CreateClient is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.CreateClientParams
func (_e *MockRepository_Expecter) CreateClient(ctx interface{}, arg interface{}) *MockRepository_CreateClient_Call {
	return &MockRepository_CreateClient_Call{Call: _e.mock.On("CreateClient", ctx, arg)}
}

func (_c *MockRepository_CreateClient_Call) Run(run func(ctx context.Context, arg store.CreateClientParams)) *MockRepository_CreateClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.CreateClientParams
		if args[1] != nil {
			arg1 = args[1].(store.CreateClientParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateClient_Call) Return(client store.Client, err error) *MockRepository_CreateClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockRepository_CreateClient_Call) RunAndReturn(run func(ctx context.Context, arg store.CreateClientParams) (store.Client, error)) *MockRepository_CreateClient_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClient provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteClient(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClient'
type MockRepository_DeleteClient_Call struct {
	*mock.Call
}

// DeleteClient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) DeleteClient(ctx interface{}, id interface{}) *MockRepository_DeleteClient_Call {
	return &MockRepository_DeleteClient_Call{Call: _e.mock.On("DeleteClient", ctx, id)}
}

func (_c *MockRepository_DeleteClient_Call) Run(run func(ctx context.Context, id string)) *MockRepository_DeleteClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteClient_Call) Return(err error) *MockRepository_DeleteClient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteClient_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_DeleteClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function for the type MockRepository
func (_mock *MockRepository) GetClient(ctx context.Context, id string) (store.Client, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 store.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (store.Client, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) store.Client); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(store.Client)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockRepository_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetClient(ctx interface{}, id interface{}) *MockRepository_GetClient_Call {
	return &MockRepository_GetClient_Call{Call: _e.mock.On("GetClient", ctx, id)}
}

func (_c *MockRepository_GetClient_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetClient_Call) Return(client store.Client, err error) *MockRepository_GetClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockRepository_GetClient_Call) RunAndReturn(run func(ctx context.Context, id string) (store.Client, error)) *MockRepository_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// ListClients provides a mock function for the type MockRepository
func (_mock *MockRepository) ListClients(ctx context.Context, arg store.ListClientsParams) ([]store.Client, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListClients")
	}

	var r0 []store.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.ListClientsParams) ([]store.Client, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.ListClientsParams) []store.Client); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.ListClientsParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClients'
type MockRepository_ListClients_Call struct {
	*mock.Call
}

// ListClients is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.ListClientsParams
func (_e *MockRepository_Expecter) ListClients(ctx interface{}, arg interface{}) *MockRepository_ListClients_Call {
	return &MockRepository_ListClients_Call{Call: _e.mock.On("ListClients", ctx, arg)}
}

func (_c *MockRepository_ListClients_Call) Run(run func(ctx context.Context, arg store.ListClientsParams)) *MockRepository_ListClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.ListClientsParams
		if args[1] != nil {
			arg1 = args[1].(store.ListClientsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListClients_Call) Return(clients []store.Client, err error) *MockRepository_ListClients_Call {
	_c.Call.Return(clients, err)
	return _c
}

func (_c *MockRepository_ListClients_Call) RunAndReturn(run func(ctx context.Context, arg store.ListClientsParams) ([]store.Client, error)) *MockRepository_ListClients_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClient provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateClient(ctx context.Context, arg store.UpdateClientParams) (store.Client, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClient")
	}

	var r0 store.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.UpdateClientParams) (store.Client, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.UpdateClientParams) store.Client); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(store.Client)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.UpdateClientParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClient'
type MockRepository_UpdateClient_Call struct {
	*mock.Call
}

// UpdateClient is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.UpdateClientParams
func (_e *MockRepository_Expecter) UpdateClient(ctx interface{}, arg interface{}) *MockRepository_UpdateClient_Call {
	return &MockRepository_UpdateClient_Call{Call: _e.mock.On("UpdateClient", ctx, arg)}
}

func (_c *MockRepository_UpdateClient_Call) Run(run func(ctx context.Context, arg store.UpdateClientParams)) *MockRepository_UpdateClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.UpdateClientParams
		if args[1] != nil {
			arg1 = args[1].(store.UpdateClientParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateClient_Call) Return(client store.Client, err error) *MockRepository_UpdateClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockRepository_UpdateClient_Call) RunAndReturn(run func(ctx context.Context, arg store.UpdateClientParams) (store.Client, error)) *MockRepository_UpdateClient_Call {
	_c.Call.Return(run)
	return _c
}
