// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client.sql

package store

import (
	"context"
)

const createClient = `-- name: CreateClient :one
INSERT INTO client (
    id,
    name,
    description,
    secret,
    scope,
    redirect_uris,
    post_logout_redirect_uris,
    grant_types,
    response_types,
    audience,
    token_endpoint_auth_method,
    application_type,
    access_token_type,
    login_url,
    id_token_lifetime_seconds,
    dev_mode,
    clock_skew_seconds,
    id_token_userinfo_claims_assertion,
    created_by,
    updated_by
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17, $18, $19, $20
)
RETURNING id, name, description, secret, scope, redirect_uris, post_logout_redirect_uris, grant_types, response_types, audience, token_endpoint_auth_method, application_type, access_token_type, login_url, id_token_lifetime_seconds, dev_mode, clock_skew_seconds, id_token_userinfo_claims_assertion, created_by, updated_by, created_at, updated_at
`

type CreateClientParams struct {
	ID                             string
	Name                           string
	Description                    string
	Secret                         string
	Scope                          string
	RedirectUris                   string
	PostLogoutRedirectUris         string
	GrantTypes                     string
	ResponseTypes                  string
	Audience                       string
	TokenEndpointAuthMethod        string
	ApplicationType                string
	AccessTokenType                string
	LoginUrl                       string
	IDTokenLifetimeSeconds         int32
	DevMode                        bool
	ClockSkewSeconds               int32
	IDTokenUserinfoClaimsAssertion bool
	CreatedBy                      string
	UpdatedBy                      string
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Secret,
		arg.Scope,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.Audience,
		arg.TokenEndpointAuthMethod,
		arg.ApplicationType,
		arg.AccessTokenType,
		arg.LoginUrl,
		arg.IDTokenLifetimeSeconds,
		arg.DevMode,
		arg.ClockSkewSeconds,
		arg.IDTokenUserinfoClaimsAssertion,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Secret,
		&i.Scope,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.Audience,
		&i.TokenEndpointAuthMethod,
		&i.ApplicationType,
		&i.AccessTokenType,
		&i.LoginUrl,
		&i.IDTokenLifetimeSeconds,
		&i.DevMode,
		&i.ClockSkewSeconds,
		&i.IDTokenUserinfoClaimsAssertion,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM client WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, name, description, secret, scope, redirect_uris, post_logout_redirect_uris, grant_types, response_types, audience, token_endpoint_auth_method, application_type, access_token_type, login_url, id_token_lifetime_seconds, dev_mode, clock_skew_seconds, id_token_userinfo_claims_assertion, created_by, updated_by, created_at, updated_at FROM client WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClient(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Secret,
		&i.Scope,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.Audience,
		&i.TokenEndpointAuthMethod,
		&i.ApplicationType,
		&i.AccessTokenType,
		&i.LoginUrl,
		&i.IDTokenLifetimeSeconds,
		&i.DevMode,
		&i.ClockSkewSeconds,
		&i.IDTokenUserinfoClaimsAssertion,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, description, secret, scope, redirect_uris, post_logout_redirect_uris, grant_types, response_types, audience, token_endpoint_auth_method, application_type, access_token_type, login_url, id_token_lifetime_seconds, dev_mode, clock_skew_seconds, id_token_userinfo_claims_assertion, created_by, updated_by, created_at, updated_at FROM client
ORDER BY created_at DESC
OFFSET $1 LIMIT $2
`

type ListClientsParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Secret,
			&i.Scope,
			&i.RedirectUris,
			&i.PostLogoutRedirectUris,
			&i.GrantTypes,
			&i.ResponseTypes,
			&i.Audience,
			&i.TokenEndpointAuthMethod,
			&i.ApplicationType,
			&i.AccessTokenType,
			&i.LoginUrl,
			&i.IDTokenLifetimeSeconds,
			&i.DevMode,
			&i.ClockSkewSeconds,
			&i.IDTokenUserinfoClaimsAssertion,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE client
SET
    name = $1,
    description = $2,
    secret = $3,
    scope = $4,
    redirect_uris = $5,
    post_logout_redirect_uris = $6,
    grant_types = $7,
    response_types = $8,
    audience = $9,
    token_endpoint_auth_method = $10,
    application_type = $11,
    access_token_type = $12,
    login_url = $13,
    id_token_lifetime_seconds = $14,
    dev_mode = $15,
    clock_skew_seconds = $16,
    id_token_userinfo_claims_assertion = $17,
    updated_by = $18,
    updated_at = now()
WHERE id = $19
RETURNING id, name, description, secret, scope, redirect_uris, post_logout_redirect_uris, grant_types, response_types, audience, token_endpoint_auth_method, application_type, access_token_type, login_url, id_token_lifetime_seconds, dev_mode, clock_skew_seconds, id_token_userinfo_claims_assertion, created_by, updated_by, created_at, updated_at
`

type UpdateClientParams struct {
	Name                           string
	Description                    string
	Secret                         string
	Scope                          string
	RedirectUris                   string
	PostLogoutRedirectUris         string
	GrantTypes                     string
	ResponseTypes                  string
	Audience                       string
	TokenEndpointAuthMethod        string
	ApplicationType                string
	AccessTokenType                string
	LoginUrl                       string
	IDTokenLifetimeSeconds         int32
	DevMode                        bool
	ClockSkewSeconds               int32
	IDTokenUserinfoClaimsAssertion bool
	UpdatedBy                      string
	ID                             string
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.Name,
		arg.Description,
		arg.Secret,
		arg.Scope,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.Audience,
		arg.TokenEndpointAuthMethod,
		arg.ApplicationType,
		arg.AccessTokenType,
		arg.LoginUrl,
		arg.IDTokenLifetimeSeconds,
		arg.DevMode,
		arg.ClockSkewSeconds,
		arg.IDTokenUserinfoClaimsAssertion,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Secret,
		&i.Scope,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.Audience,
		&i.TokenEndpointAuthMethod,
		&i.ApplicationType,
		&i.AccessTokenType,
		&i.LoginUrl,
		&i.IDTokenLifetimeSeconds,
		&i.DevMode,
		&i.ClockSkewSeconds,
		&i.IDTokenUserinfoClaimsAssertion,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
