// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/tuanta7/ciam/pkg/sqlx"
)

type Client struct {
	ID                             string
	Name                           string
	Description                    string
	Secret                         string
	Scope                          sqlx.StringArray
	RedirectUris                   sqlx.StringArray
	PostLogoutRedirectUris         sqlx.StringArray
	GrantTypes                     sqlx.StringArray
	ResponseTypes                  sqlx.StringArray
	Audience                       sqlx.StringArray
	TokenEndpointAuthMethod        string
	ApplicationType                string
	AccessTokenType                string
	LoginUrl                       string
	IDTokenLifetimeSeconds         int32
	DevMode                        bool
	ClockSkewSeconds               int32
	IDTokenUserinfoClaimsAssertion bool
	CreatedBy                      string
	UpdatedBy                      string
	CreatedAt                      pgtype.Timestamp
	UpdatedAt                      pgtype.Timestamp
}
