// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID                             string
	Name                           string
	Description                    string
	Secret                         string
	Scope                          string
	RedirectUris                   string
	PostLogoutRedirectUris         string
	GrantTypes                     string
	ResponseTypes                  string
	Audience                       string
	TokenEndpointAuthMethod        string
	ApplicationType                string
	AccessTokenType                string
	LoginUrl                       string
	IDTokenLifetimeSeconds         int32
	DevMode                        bool
	ClockSkewSeconds               int32
	IDTokenUserinfoClaimsAssertion bool
	CreatedBy                      string
	UpdatedBy                      string
	CreatedAt                      pgtype.Timestamp
	UpdatedAt                      pgtype.Timestamp
}
